### ISSUE TITLE
Selenium version provided by this package is outdated

### ISSUE THREAD

**Issue by JaimeObregon** [Emagister/selenium-server#5]
The documentation states that _"we will maintain the repository updated with the latest stable version of Selenium"_. How ever Selenium server's version provided by this package is 2.44, which is over a year old and causes a `org.openqa.selenium.firefox.NotConnectedException` with Firefox latest versions.

I'd suggest updating this package on a regular basis or removing the aforementioned statement from the `README.md`.

**Comment by JaimeObregon** [comment]
@tilibom Please find the attached pull request. It might be useful to [update Packagist](https://packagist.org/packages/emagister/selenium-server) as well. Hope this helps ;-)

**Comment by sorbing** [comment]
Hi. Please, update your package.
